[ADD] mail_outbound_static: Backport a v10 de modulo de correos
TRESCLOUD/social pull request #1
Opened 2020-07-08 03:18 UTC by rquevedo

2020-07-08 22:05 UTC, pepetreshere requested changes

2020-07-08 22:05 UTC, pepetreshere commented on mail_outbound_static/README.rst
> +* Lorenzo Battistini <https://github.com/eLBati>
Pon aquí a trescloud, a tu persona, y a mi persona

2020-07-08 22:05 UTC, pepetreshere commented on mail_outbound_static/readme/CONTRIBUTORS.rst
> +* Lorenzo Battistini <https://github.com/eLBati>
Elimina este archivo

2020-07-08 22:05 UTC, pepetreshere commented on mail_outbound_static/tests/test.msg
> +        b=E2B6KUxHOJQk1YrT12BpitEMCgkxyqEXcFlwPWKjA/i/Xyvlh+09spNOF4VPmD/ZJm
Todo este archivo se ejecuto? si no hicimos pruebas unitarias (que asumo es esto) no lo pongamos

2020-07-08 22:05 UTC, pepetreshere commented on mail_outbound_static/readme/USAGE.rst
> +* Set the `Email From` option to an email address
Pudimos agregar la opción al archivo de configuración odoo.conf?? por favor agreguemos y expliquemos eso en alguna parte del readme.rst del usage.rst o de alguna de las partes

2020-07-08 22:05 UTC, pepetreshere commented on mail_outbound_static/i18n/mail_outbound_static.pot
> +msgid ""
Remover este archivo, la OCA no acepta traducciones vía .po sino solamente vía una plataforma web externa

2020-07-08 22:05 UTC, pepetreshere commented on mail_outbound_static/__manifest__.py
> +    'author': 'LasLabs, Odoo Community Association (OCA)',
Incluir a Trescloud

2020-07-09 03:28 UTC, rquevedo commented on mail_outbound_static/README.rst
> +* Lorenzo Battistini <https://github.com/eLBati>
Listo

2020-07-09 03:29 UTC, rquevedo commented on mail_outbound_static/readme/CONTRIBUTORS.rst
> +* Lorenzo Battistini <https://github.com/eLBati>
Listo

2020-07-09 03:29 UTC, rquevedo commented on mail_outbound_static/readme/USAGE.rst
> +* Set the `Email From` option to an email address
Listo

2020-07-09 03:29 UTC, rquevedo commented on mail_outbound_static/__manifest__.py
> +    'author': 'LasLabs, Odoo Community Association (OCA)',
Listo

2020-07-09 03:29 UTC, rquevedo commented on mail_outbound_static/i18n/mail_outbound_static.pot
> +msgid ""
Listo

2020-07-09 03:29 UTC, rquevedo commented on mail_outbound_static/tests/test.msg
> +        b=E2B6KUxHOJQk1YrT12BpitEMCgkxyqEXcFlwPWKjA/i/Xyvlh+09spNOF4VPmD/ZJm
Listo

2020-07-09 23:54 UTC, pepetreshere requested changes

2020-07-09 23:54 UTC, pepetreshere commented on mail_outbound_static/__manifest__.py
> +    'author': 'LasLabs, Odoo Community Association (OCA), TRESCLOUD CIA. LTDA.',
```suggestion
    'author': 'LasLabs, Trescloud, Odoo Community Association (OCA)',
```

2020-07-09 23:55 UTC, merged